version: 2.1

workflows:
  run-test-workflow:
    jobs:
      - run-e2e-tests

jobs:
  run-e2e-tests:
    docker:
      - image: cimg/base:2023.11
    parallelism: 4
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: List test files
          command: ls ./src/e2e/tests/*.spec.ts
      - run:
          name: Run tests
          command: |
            mkdir test-results
            pnpm run serve &
            TESTFILES=$(circleci tests glob "./src/e2e/tests/*.spec.ts")
            echo "$TESTFILES" | circleci tests run --command="xargs pnpm playwright test --config=playwright.config.ci.ts --reporter=junit" --verbose --split-by=timings
      - store_test_results:
          path: results.xml
